### ISSUE TITLE
tudou会执行两次script.js文件？

### ISSUE THREAD

**Issue by ghyghoo8** [ghyghoo8/ADclearer#1]
发现一个bug，tudou会执行两次： UTIL.forEach(CONTROLLER, PROC);
其中一次的 document.title="nothing here"

找到一个判断：this.parent == this
还有啥其他办法判断 js是否在iframe中

**Comment by ghyghoo8** [comment]
尼玛～有个 url=http://ui.tudou.com/js/embed/xstorage/storage.html 的iframe 。。。

**Comment by ghyghoo8** [comment]
需要判断iframe

**Comment by dongjun111111** [comment]
试用一下

**Comment by dongjun111111** [comment]
：）
